### PR TITLE
Fixed cydia not installing bug

### PR DESCRIPTION
**Pull request by leoskingsley**
There is a double negative when checking whether to install. It checks if it exists, and negates it. It is then compared to `YES` with a `!=` operator, meaning Cydia won't be installed if it can't be found on the device.

### CODE REVIEW

**Comment by Crystallux** [comment]
This was on purpose though

**Comment by leoskingsley** [comment]
It’s been marked as a bug in issues

**Comment by leoskingsley** [comment]
Well no because then you may aswell not perform the checks.

**Comment by Jamal-Hassan** [comment]
This bug is also occurring on iPhone X iOS 11.1.2,
To.Panga app promotes “Finished” after jailbreak but cydia isn’t appearing.

**Comment by Johntpeterson** [comment]
Cydia is being phased out in favor of jjjj. The only reason that cydia is still in to.panga is because it's files are neccesary in ways I don't totally understand.

Cydia.app is useless without working HTTP and @iabem97 has expressed desire not to include a fix in later releases (#11)

**Comment by iabem97** [comment]
thank you but this was done on purpose since I already have Cydia.app installed and I need the untar function to run every time. Closing since this isn't really an issue.

**Pull request closed without merging**
